name: Auto Update Stock HTML

on:
 schedule:
    - cron: '0 * * * *'  # 每 1 小时自动拉取数据并重新渲染 HTML 页面
  workflow_dispatch:          # 支持在 GitHub 界面手动触发更新

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Update Script
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          DEEPSEEK_KEY: ${{ secrets.DEEPSEEK_KEY }}
        run: python script.py

      - name: Commit and Push index.html
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto update index.html" || exit 0
          git push
